import { useEffect, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import api from '../api/axios'
import { ApiErrorState, Button, PriceTag, Toast } from '../components/ui'

function OrderDetail() {
  const { id } = useParams(); const location = useLocation(); const [order, setOrder] = useState(null); const [error, setError] = useState(location.state?.error || ''); const [toast, setToast] = useState('')
  const load = () => { setError(''); setOrder(null); api.get(`/orders/${id}`).then(({ data }) => setOrder(data)).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load order.')) }
  useEffect(() => { load() }, [id])
  const cancel = async () => { try { const { data } = await api.put(`/orders/${id}/cancel`); setOrder(data); setToast('Order cancelled and stock restored.') } catch (requestError) { setToast(requestError.response?.data?.message || 'Unable to cancel order.') } }
  const retryPayment = async () => { try { const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; await new Promise((resolve, reject) => { script.onload = resolve; script.onerror = reject; document.body.appendChild(script) }); const { data: payment } = await api.post('/payment/create', { orderId: id }); new window.Razorpay({ key: payment.keyId, amount: payment.amount, currency: payment.currency, order_id: payment.orderId, name: 'NEXORA', handler: async (response) => { try { const { data } = await api.post('/payment/verify', { orderId: id, razorpayOrderId: response.razorpay_order_id, razorpayPaymentId: response.razorpay_payment_id, razorpaySignature: response.razorpay_signature }); setOrder(data); setToast('Payment received.') } catch (requestError) { setToast(requestError.response?.data?.message || 'Payment verification failed.') } } }).open() } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to retry payment.') } }
  if (!order) return <section className="container page-section">{error ? <ApiErrorState message={error} onRetry={load} /> : <p className="status-message">Loading order...</p>}</section>
  return <section className="container page-section order-detail-page"><Link className="text-link" to="/orders">← All orders</Link><p className="eyebrow">Order {order._id.slice(-8).toUpperCase()}</p><h1>Order details</h1>{error && <p className="form-error" role="alert">{error}</p>}<p className={`order-status status-${order.status}`}>{order.status}</p><div className="order-items">{order.items.map((item) => <div className="order-row" key={item._id}><span>{item.name} × {item.qty}</span><PriceTag price={item.price * item.qty} /></div>)}</div><div className="local-list-summary"><div><span>Items</span><strong><PriceTag price={order.itemsPrice} /></strong></div><div><span>Shipping</span><strong><PriceTag price={order.shippingPrice} /></strong></div><div><span>Total</span><strong><PriceTag price={order.totalPrice} /></strong></div>{order.status === 'pending' && order.paymentMethod === 'razorpay' && <Button type="button" onClick={retryPayment}>Retry payment</Button>}{['pending', 'paid'].includes(order.status) && <Button variant="secondary" type="button" onClick={cancel}>Cancel order</Button>}</div><Toast message={toast} onClose={() => setToast('')} /></section>
}

export default OrderDetail