import mongoose from 'mongoose';
import Order from '../models/Order.js';
import Product from '../models/Product.js';
import User from '../models/User.js';

const pageData = (req) => ({ page: Math.max(1, Number(req.query.page) || 1), limit: Math.min(50, Math.max(1, Number(req.query.limit) || 20)) });
export const getStats = async (req, res, next) => { try { const since = new Date(); since.setHours(0, 0, 0, 0); since.setDate(since.getDate() - 6); const [totalUsers, totalOrders, revenue, pendingOrders, lowStockProducts, daily, categoryCounts, recentOrders] = await Promise.all([User.countDocuments(), Order.countDocuments(), Order.aggregate([{ $match: { status: { $ne: 'cancelled' } } }, { $group: { _id: null, total: { $sum: '$totalPrice' } } }]), Order.countDocuments({ status: 'pending' }), Product.find({ stock: { $lt: 5 } }).select('name stock images').sort({ stock: 1 }).limit(10), Order.aggregate([{ $match: { createdAt: { $gte: since }, status: { $ne: 'cancelled' } } }, { $group: { _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } }, orders: { $sum: 1 }, revenue: { $sum: '$totalPrice' } } }, { $sort: { _id: 1 } }]), Product.aggregate([{ $group: { _id: '$category', count: { $sum: 1 } } }, { $sort: { _id: 1 } }]), Order.find().populate('user', 'name email').sort({ createdAt: -1 }).limit(8)]); res.json({ totalUsers, totalOrders, revenue: revenue[0]?.total || 0, pendingOrders, lowStockProducts, daily, categoryCounts, recentOrders }); } catch (error) { next(error); } };
export const listUsers = async (req, res, next) => { try { const { page, limit } = pageData(req); const filter = req.query.search ? { $or: [{ name: new RegExp(req.query.search, 'i') }, { email: new RegExp(req.query.search, 'i') }] } : {}; const [users, total] = await Promise.all([User.find(filter).select('-password').sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), User.countDocuments(filter)]); res.json({ users, total, page, pages: Math.ceil(total / limit) }); } catch (error) { next(error); } };
export const changeUserRole = async (req, res, next) => { try { if (req.params.id === req.user._id.toString()) return res.status(400).json({ message: 'You cannot change your own role' }); if (!['user', 'admin'].includes(req.body.role)) return res.status(400).json({ message: 'Invalid role' }); const user = await User.findByIdAndUpdate(req.params.id, { role: req.body.role }, { new: true }).select('-password'); if (!user) return res.status(404).json({ message: 'User not found' }); res.json(user); } catch (error) { next(error); } };
export const deleteUser = async (req, res, next) => { try { if (req.params.id === req.user._id.toString()) return res.status(400).json({ message: 'You cannot delete yourself' }); const user = await User.findByIdAndDelete(req.params.id); if (!user) return res.status(404).json({ message: 'User not found' }); res.json({ message: 'User deleted' }); } catch (error) { next(error); } };
export const listOrders = async (req, res, next) => { try { const { page, limit } = pageData(req); const filter = req.query.status ? { status: req.query.status } : {}; const [orders, total] = await Promise.all([Order.find(filter).populate('user', 'name email').sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), Order.countDocuments(filter)]); res.json({ orders, total, page, pages: Math.ceil(total / limit) }); } catch (error) { next(error); } };
const transitions = { pending: ['paid', 'cancelled'], paid: ['shipped', 'cancelled'], shipped: ['delivered'], delivered: [], cancelled: [] };
export const updateOrderStatus = async (req, res, next) => { try { const order = await Order.findById(req.params.id); if (!order) return res.status(404).json({ message: 'Order not found' }); const nextStatus = req.body.status; if (!transitions[order.status]?.includes(nextStatus)) return res.status(400).json({ message: `Cannot move order from ${order.status} to ${nextStatus}` }); if (nextStatus === 'cancelled') await Promise.all(order.items.map((item) => Product.updateOne({ _id: item.product }, { $inc: { stock: item.qty } }))); order.status = nextStatus; if (nextStatus === 'paid') { order.isPaid = true; order.paidAt ||= new Date(); } await order.save(); res.json(order); } catch (error) { next(error); } };